"""Packaged unified-tool specifications (package data).

``index.json`` and ``tools/<tool>.json`` in this package are generated by
``scripts/build_unified_tool_specs.py`` and are byte-identical to
``docs/unified-tools/``. Never edit them by hand.
"""

from __future__ import annotations

import json
from functools import cache
from importlib.resources import files
from typing import Any

__all__ = ["load_index", "load_tool_spec"]


@cache
def _read(relative_path: str) -> str:
    return files(__name__).joinpath(relative_path).read_text(encoding="utf-8")


def load_index() -> dict[str, Any]:
    """Load the packaged spec index (tool order, tiers, resources).

    Returns:
        A fresh copy of the parsed ``index.json``.
    """
    return json.loads(_read("index.json"))


def load_tool_spec(name: str) -> dict[str, Any]:
    """Load one packaged tool specification.

    Args:
        name: Unified tool name listed in ``index.json``.

    Returns:
        A fresh copy of the parsed ``tools/<name>.json``.

    Raises:
        KeyError: If ``name`` is not a tool in the index.
    """
    if name not in load_index()["tool_order"]:
        raise KeyError(f"Unknown unified tool {name!r}")
    return json.loads(_read(f"tools/{name}.json"))
