from __future__ import annotations

import pytest

from m365_mcp.tools import mcp


EXPECTED_TOOL_NAMES = {
    "account_authenticate",
    "account_complete_auth",
    "account_list",
    "cache_get_stats",
    "cache_invalidate",
    "cache_task_get_status",
    "cache_task_list",
    "cache_warming_status",
    "calendar_check_availability",
    "calendar_create_calendar",
    "calendar_create_event",
    "calendar_delete_calendar",
    "calendar_delete_event",
    "calendar_forward_event",
    "calendar_get_event",
    "calendar_get_free_busy",
    "calendar_list_calendars",
    "calendar_list_events",
    "calendar_propose_new_time",
    "calendar_respond_event",
    "calendar_update_event",
    "contact_add_to_list",
    "contact_create",
    "contact_create_list",
    "contact_delete",
    "contact_export",
    "contact_get",
    "contact_list",
    "contact_update",
    "email_add_category",
    "email_archive",
    "email_create_draft",
    "email_delete",
    "email_flag",
    "email_forward",
    "email_get",
    "email_get_attachment",
    "email_list",
    "email_mark_read",
    "email_move",
    "email_reply",
    "email_reply_all",
    "email_send",
    "email_update",
    "emailfolders_create",
    "emailfolders_delete",
    "emailfolders_empty",
    "emailfolders_get",
    "emailfolders_get_tree",
    "emailfolders_list",
    "emailfolders_mark_all_as_read",
    "emailfolders_move",
    "emailfolders_rename",
    "emailrules_create",
    "emailrules_delete",
    "emailrules_get",
    "emailrules_list",
    "emailrules_move_bottom",
    "emailrules_move_down",
    "emailrules_move_top",
    "emailrules_move_up",
    "emailrules_update",
    "file_copy",
    "file_create",
    "file_delete",
    "file_download_url",
    "file_get",
    "file_list",
    "file_move",
    "file_rename",
    "file_share",
    "file_update",
    "folder_create",
    "folder_delete",
    "folder_get",
    "folder_get_tree",
    "folder_list",
    "folder_move",
    "folder_rename",
    "search_contacts",
    "search_emails",
    "search_events",
    "search_files",
    "search_unified",
    "server_get_version",
}


@pytest.mark.asyncio
async def test_runtime_tool_surface_matches_expected_public_tools() -> None:
    tools = await mcp.get_tools()

    assert set(tools) == EXPECTED_TOOL_NAMES
    assert len(tools) == 85
